# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwifterSwiftDemo' do
  use_frameworks!
  pod 'SwifterSwift', '~> 1.3.2'
  # Pods for SwifterSwiftDemo

end
